export interface Product {
    id: string;
    title: string;
    price: string;
    regularPrice?: string;
    image: string;
    category: string;
    description: string;
    slug: string;
    sku: string;
    subscription?: boolean;
    featured?: boolean;
    badge?: string;
    highlights?: string[];
    ingredients?: string[];
    benefits?: string[];
    howToUse?: string[];
    variants?: Array<{
        id: string;
        title?: string;
        size: string;
        weight: string;
        price: number;
        originalPrice?: number;
        inStock: boolean;
        inventory?: number;
    }>;
}

export const products: Product[] = [
    // ═══════════════════════════════════════════════════════════
    // GHEE (Moved to Top)
    // ═══════════════════════════════════════════════════════════
    {
        id: "ghee-cow-1kg",
        title: "Amrit Milk Organic A2 Cow Ghee",
        price: "₹2500",
        image: "/assets/img/products/amrit_ghee_premium.png",
        category: "Ghee",
        description: "Traditional Bilona method A2 Cow Ghee. Pure gold for health.",
        slug: "a2-cow-ghee-1kg",
        sku: "AMRIT-DAIRY-005",
        featured: true,
        badge: "Pure Vedic",
        variants: [
            {
                id: "1kg",
                title: "1 L",
                size: "1kg",
                weight: "1 kilogram",
                price: 2500,
                originalPrice: 2700,
                inStock: true,
                inventory: 15,
            },
            {
                id: "500gm",
                title: "500 ml",
                size: "500gm",
                weight: "500 grams",
                price: 1350,
                originalPrice: 1400,
                inStock: true,
                inventory: 25,
            },
        ],
        highlights: [
            "Made using traditional Bilona hand-churning method",
            "100% A2 beta-casein protein from Desi Gir cows",
            "Rich golden color and aromatic fragrance",
            "Chemical-free | Preservative-free | Grain-fed cows",
        ],
        ingredients: ["Pure A2 Desi Gir Cow Milk", "Natural cultures for curd formation"],
        benefits: [
            "Strengthens immunity and digestive fire (Agni)",
            "Promotes healthy bones, brain development",
            "Rich in Omega-3 fatty acids and fat-soluble vitamins (A, D, E, K)",
            "Ideal for cooking, tadka, and spiritual offerings",
            "Supports healthy cholesterol levels",
        ],
        howToUse: [
            "Use for daily cooking, especially for tadka and sautéing",
            "Consume 1-2 teaspoons with warm milk or meals",
            "Apply topically for skin nourishment and massage",
            "Ideal for traditional Indian sweets and rituals",
        ],
    },
    {
        id: "ghee-cow-500ml",
        title: "Amrit Milk Organic A2 Cow Ghee",
        price: "₹1350",
        image: "/assets/img/products/amrit_ghee_premium.png",
        category: "Ghee",
        description: "Traditional Bilona method A2 Cow Ghee. Pure gold for health.",
        slug: "a2-cow-ghee-500ml",
        sku: "AMRIT-DAIRY-005-SM",
        variants: [
            {
                id: "500gm",
                title: "500 ml",
                size: "500gm",
                weight: "500 grams",
                price: 1350,
                originalPrice: 1400,
                inStock: true,
                inventory: 25,
            },
            {
                id: "1kg",
                title: "1 L",
                size: "1kg",
                weight: "1 kilogram",
                price: 2500,
                originalPrice: 2700,
                inStock: true,
                inventory: 15,
            },
        ],
        highlights: [
            "Made using traditional Bilona hand-churning method",
            "100% A2 beta-casein protein from Desi Gir cows",
            "Compact 500ml size perfect for trying or gifting",
            "Chemical-free | Preservative-free | Grain-fed cows",
        ],
        ingredients: ["Pure A2 Desi Gir Cow Milk", "Natural cultures for curd formation"],
        benefits: [
            "Strengthens immunity and digestive fire (Agni)",
            "Promotes healthy bones, brain development",
            "Rich in Omega-3 fatty acids and fat-soluble vitamins (A, D, E, K)",
            "Ideal for cooking, tadka, and spiritual offerings",
            "Supports healthy cholesterol levels",
        ],
        howToUse: [
            "Use for daily cooking, especially for tadka and sautéing",
            "Consume 1-2 teaspoons with warm milk or meals",
            "Apply topically for skin nourishment and massage",
            "Ideal for traditional Indian sweets and rituals",
        ],
    },

    // ═══════════════════════════════════════════════════════════
    // ESSENTIAL OILS (Tulsi, Lemongrass, Menthol) - Requested Order
    // ═══════════════════════════════════════════════════════════
    {
        id: "oil-tulsi-10ml",
        title: "Amrit Organic Tulsi Oil - 10 ml",
        price: "₹300",
        image: "/assets/img/products/amrit_oil_tulsi_rollon.png",
        category: "Essential Oils",
        description: "Sacred Tulsi essential oil. Cold-pressed & distilled.",
        slug: "tulsi-oil-10ml",
        sku: "AMRIT-OIL-006",
        featured: true,
        highlights: [
            "Pure steam-distilled Tulsi (Holy Basil) oil",
            "Therapeutic grade essential oil",
            "Potent adaptogenic properties",
            "100% natural | No synthetic additives",
        ],
        ingredients: ["Pure Tulsi (Ocimum sanctum) leaves and flowers"],
        benefits: [
            "Reduces stress, anxiety, and promotes mental clarity",
            "Boosts immunity and respiratory health",
            "Natural antimicrobial and anti-inflammatory",
            "Ideal for aromatherapy and diffusion",
            "Supports skin health when diluted",
        ],
        howToUse: [
            "Add 2-3 drops to a diffuser for aromatherapy",
            "Dilute with carrier oil for topical application",
            "Mix 1-2 drops with steam water for inhalation (cold relief)",
            "Never consume undiluted essential oil",
        ],
    },
    {
        id: "oil-lemongrass-10ml",
        title: "Amrit Organic Lemongrass Oil - 10 ml",
        price: "₹400",
        image: "/assets/img/products/amrit_lemongrass_oil_v6.png",
        category: "Essential Oils",
        description: "Refreshing Lemongrass essential oil. Cold-pressed & distilled.",
        slug: "lemongrass-oil-10ml",
        sku: "AMRIT-OIL-007",
        featured: true,
        highlights: [
            "Pure steam-distilled Lemongrass oil",
            "Fresh, citrusy, uplifting aroma",
            "Therapeutic grade essential oil",
            "100% natural | No synthetic fragrances",
        ],
        ingredients: ["Pure Lemongrass (Cymbopogon citratus) leaves"],
        benefits: [
            "Natural insect and mosquito repellent",
            "Relieves headaches, body pain, and fatigue",
            "Antimicrobial and anti-fungal properties",
            "Boosts mood and mental energy",
            "Detoxifies and tones skin when diluted",
        ],
        howToUse: [
            "Add 3-4 drops to diffuser for fresh, clean air",
            "Dilute with carrier oil for massage or skin application",
            "Mix with water in spray bottle for natural air freshener",
            "Add to bathwater for relaxation (2-3 drops with carrier oil)",
        ],
    },
    {
        id: "oil-menthol-10ml",
        title: "Amrit Organic Mint Oil - 10 ml",
        price: "₹250",
        image: "/assets/img/products/amrit_mint_oil_v6.png",
        category: "Essential Oils",
        description: "Cooling Mint essential oil. Cold-pressed & distilled.",
        slug: "menthol-oil-10ml",
        sku: "AMRIT-OIL-008",
        featured: true,
        highlights: [
            "Pure steam-distilled Peppermint/Mentha oil",
            "Intensely cooling and refreshing",
            "Therapeutic grade essential oil",
            "100% natural | No synthetic menthol",
        ],
        ingredients: ["Pure Peppermint (Mentha piperita) leaves"],
        benefits: [
            "Instant relief from headaches and migraines",
            "Clears nasal congestion and respiratory issues",
            "Reduces muscle pain and inflammation",
            "Boosts energy, focus, and mental alertness",
            "Soothes digestive discomfort when diluted",
        ],
        howToUse: [
            "Add 2-3 drops to diffuser for cooling aromatherapy",
            "Dilute with carrier oil, apply to temples for headache relief",
            "Inhale directly from bottle or add to steam for congestion",
            "Mix 1 drop with carrier oil for cooling massage",
        ],
    },

    // ═══════════════════════════════════════════════════════════
    // HONEY (Moved up, between Essential and Cooking Oils)
    // ═══════════════════════════════════════════════════════════
    {
        id: "honey-multiflora-1kg",
        title: "Amrit Organic Multiflora Honey",
        price: "₹400",
        image: "/assets/img/products/amrit_honey_premium_v7.png",
        category: "Honey",
        description: "Pure Multiflora honey collected from diverse forest flowers.",
        slug: "multiflora-honey-1kg",
        sku: "AMRIT-HONEY-001",
        featured: true,
        badge: "Raw & Pure",
        variants: [
            {
                id: "300gm",
                title: "300 gm",
                size: "300gm",
                weight: "300 grams",
                price: 400,
                inStock: true,
                inventory: 30,
            },
            {
                id: "1kg",
                title: "1 kg",
                size: "1kg",
                weight: "1 kilogram",
                price: 1200,
                originalPrice: 1300,
                inStock: true,
                inventory: 20,
            },
        ],
        highlights: [
            "100% raw, unprocessed, unpasteurized honey",
            "Collected from diverse forest wildflowers",
            "Rich amber color with complex flavor profile",
            "No added sugar | No heating | Single-origin",
        ],
        ingredients: ["Pure nectar from wildflowers (multiflora)"],
        benefits: [
            "Natural energy booster and immunity enhancer",
            "Rich in antioxidants, enzymes, and minerals",
            "Soothes cough, cold, and sore throat",
            "Supports digestive health and gut flora",
            "Natural wound healer and skin moisturizer",
        ],
        howToUse: [
            "Consume 1-2 teaspoons daily on empty stomach or with warm water",
            "Use as natural sweetener in tea, smoothies, or desserts",
            "Apply topically on skin for glow and healing",
            "Do not heat above 40°C to preserve enzymes",
        ],
    },
    {
        id: "honey-jamun-1kg",
        title: "Amrit Organic Jamun Honey",
        price: "₹400",
        image: "/assets/img/products/amrit_jamun_honey_v3.png",
        category: "Honey",
        description: "Medicinal honey from Jamun flower nectar. Good for diabetics.",
        slug: "jamun-honey-1kg",
        sku: "AMRIT-HONEY-002",
        featured: true,
        variants: [
            {
                id: "300gm",
                title: "300 gm",
                size: "300gm",
                weight: "300 grams",
                price: 400,
                inStock: true,
                inventory: 28,
            },
            {
                id: "1kg",
                title: "1 kg",
                size: "1kg",
                weight: "1 kilogram",
                price: 1200,
                originalPrice: 1300,
                inStock: true,
                inventory: 18,
            },
        ],
        highlights: [
            "100% raw, unprocessed Jamun (Indian Blackberry) honey",
            "Low glycemic index - Diabetes-friendly",
            "Dark purple-black color with unique tangy flavor",
            "No added sugar | No heating | Single-origin",
        ],
        ingredients: ["Pure nectar from Jamun (Syzygium cumini) flowers"],
        benefits: [
            "Helps regulate blood sugar levels naturally",
            "Rich in antioxidants and iron",
            "Supports digestive health and metabolism",
            "Boosts immunity and respiratory health",
            "Ayurvedic remedy for diabetes management",
        ],
        howToUse: [
            "Consume 1 teaspoon daily on empty stomach for diabetes management",
            "Mix with warm water or herbal tea (do not heat above 40°C)",
            "Use as natural sweetener in desserts and beverages",
            "Consult with doctor if diabetic before regular consumption",
        ],
    },

    // ═══════════════════════════════════════════════════════════
    // COOKING OILS (Standard Wood Pressed)
    // ═══════════════════════════════════════════════════════════
    {
        id: "oil-yellow-mustard-1l",
        title: "Amrit Organic Yellow Mustard Oil - 1 L",
        price: "₹380",
        image: "/assets/img/products/yellow_mustard_oil.png",
        category: "Cold-Pressed Oils",
        description: "Cold-pressed Yellow Mustard oil (Kacchi Ghani).",
        slug: "yellow-mustard-oil-1l",
        sku: "AMRIT-OIL-001",
        featured: true,
        highlights: [
            "Traditional wood-pressed (Kacchi Ghani) method",
            "100% pure yellow mustard seeds",
            "Rich, pungent aroma with golden color",
            "No chemicals | No refining | Single-pressed",
        ],
        ingredients: ["Pure Yellow Mustard Seeds (Brassica hirta)"],
        benefits: [
            "Rich in Omega-3 fatty acids and antioxidants",
            "Boosts immunity and heart health",
            "Natural antibacterial and antifungal properties",
            "Ideal for pickling, cooking, and massage",
            "Promotes healthy skin and hair growth",
        ],
        howToUse: [
            "Heat lightly for cooking to reduce pungency",
            "Use for tempering (tadka) in Indian cuisine",
            "Ideal for pickling vegetables and chutneys",
            "Warm and massage for joint pain relief and hair nourishment",
        ],
    },
    {
        id: "oil-black-mustard-1l",
        title: "Amrit Organic Black Mustard Oil - 1 L",
        price: "₹350",
        image: "/assets/img/products/black_mustard_oil.png",
        category: "Cold-Pressed Oils",
        description: "Cold-pressed Black Mustard oil, pungent and pure.",
        slug: "black-mustard-oil-1l",
        sku: "AMRIT-OIL-002",
        featured: true,
        highlights: [
            "Traditional wood-pressed (Kacchi Ghani) method",
            "100% pure black mustard seeds",
            "Intense pungent flavor with dark amber color",
            "No chemicals | No refining | Single-pressed",
        ],
        ingredients: ["Pure Black Mustard Seeds (Brassica jun cea)"],
        benefits: [
            "Higher antioxidant content than yellow mustard oil",
            "Stimulates circulation and metabolism",
            "Natural pain reliever for arthritis and muscle aches",
            "Promotes healthy digestion and appetite",
            "Excellent for skin and hair care",
        ],
        howToUse: [
            "Heat lightly for cooking to reduce pungency",
            "Use for tempering (tadka) in Bengali and North Indian cuisine",
            "Ideal for pickling and marinades",
            "Warm and massage for joint pain, hair growth",
        ],
    },
    {
        id: "oil-groundnut-1l",
        title: "Amrit Organic Groundnut Oil - 1 L",
        price: "₹600",
        image: "/assets/img/products/amrit_oil_groundnut_1l_v2.png",
        category: "Cold-Pressed Oils",
        description: "Cold-pressed Groundnut oil, rich in flavor.",
        slug: "groundnut-oil-1l-premium",
        sku: "AMRIT-OIL-003",
        featured: true,
        highlights: [
            "Traditional wood-pressed (Kacchi Ghani) method",
            "100% pure groundnut (peanut) kernels",
            "Mild, nutty flavor with golden color",
            "High smoke point | No refining | Single-pressed",
        ],
        ingredients: ["Pure Groundnut Kernels (Arachis hypogaea)"],
        benefits: [
            "Rich in monounsaturated fats (heart-healthy)",
            "High in Vitamin E and antioxidants",
            "Supports healthy cholesterol levels",
            "Ideal for deep frying and high-heat cooking",
            "Promotes skin elasticity and moisture",
        ],
        howToUse: [
            "Perfect for deep frying, sautéing, and stir-frying",
            "Use in salad dressings and marinades",
            "Ideal for Indian, Chinese, and Southeast Asian cuisine",
            "Apply topically for skin nourishment and massage",
        ],
    },
    {
        id: "oil-coconut-1l",
        title: "Amrit Organic Coconut Oil - 1 L",
        price: "₹1000",
        image: "/assets/img/products/coconut_oil.png",
        category: "Cold-Pressed Oils",
        description: "Pure cold-pressed Coconut oil for cooking and care.",
        slug: "coconut-oil-1l-premium",
        sku: "AMRIT-OIL-004",
        featured: true,
        highlights: [
            "Traditional wood-pressed (Kacchi Ghani) virgin coconut oil",
            "100% pure coconut kernel (copra)",
            "Natural coconut aroma with pristine white color",
            "No heat treatment | No chemicals | Single-pressed",
        ],
        ingredients: ["Pure Coconut Kernel (Cocos nucifera)"],
        benefits: [
            "Rich in MCT (Medium Chain Triglycerides) for energy",
            "Natural antibacterial and antiviral properties",
            "Promotes healthy skin, hair, and scalp",
            "Supports metabolism and weight management",
            "Ideal for oil pulling and Ayurvedic therapies",
        ],
        howToUse: [
            "Use for cooking (solidifies below 24°C, liquifies when heated)",
            "Apply on skin and hair for deep nourishment",
            "Use for oil pulling (swish 1 tablespoon for 10-15 min on empty stomach)",
            "Ideal for baking, smoothies, and bulletproof coffee",
        ],
    },
    {
        id: "oil-sesame-1l",
        title: "Amrit Organic Sesame (Til) Oil - 1 L",
        price: "₹800",
        image: "/assets/img/products/sesame_oil.png",
        category: "Cold-Pressed Oils",
        description: "Cold-pressed Sesame (Til) oil.",
        slug: "sesame-til-oil-1l",
        sku: "AMRIT-OIL-005",
        featured: true,
        highlights: [
            "Traditional wood-pressed (Kacchi Ghani) method",
            "100% pure sesame seeds (white til)",
            "Rich, nutty aroma with golden color",
            "No chemicals | No refining | Single-pressed",
        ],
        ingredients: ["Pure White Sesame Seeds (Sesamum indicum)"],
        benefits: [
            "Rich in antioxidants (sesamol, sesamin)",
            "Supports bone health and calcium absorption",
            "Anti-inflammatory properties for joints",
            "Promotes healthy cholesterol and blood pressure",
            "Excellent for Ayurvedic massage and oil therapies",
        ],
        howToUse: [
            "Use for tempering, stir-frying, and sautéing",
            "Add to salads and Asian cuisine for nutty flavor",
            "Warm and massage for detoxification (Abhyanga)",
            "Ideal for oil pulling and scalp massage",
        ],
    },

    // ═══════════════════════════════════════════════════════════
    // OTHER PRODUCTS
    // ═══════════════════════════════════════════════════════════
    {
        id: "turmeric-1kg",
        title: "Amrit Organic Turmeric - 1 kg",
        price: "₹900",
        image: "/assets/img/products/premium_turmeric_powder.png",
        category: "Other",
        description: "High-curcumin Organic Turmeric powder.",
        slug: "organic-turmeric-1kg",
        sku: "AMRIT-MISC-001",
        highlights: [
            "100% pure organic turmeric rhizomes",
            "High curcumin content (5-7%)",
            "Vibrant golden-yellow color with earthy aroma",
            "No additives | No artificial colors | Stone-ground",
        ],
        ingredients: ["Pure Organic Turmeric Rhizomes (Curcuma longa)"],
        benefits: [
            "Powerful anti-inflammatory and antioxidant properties",
            "Boosts immunity and supports joint health",
            "Aids digestion and liver detoxification",
            "Natural remedy for colds, wounds, and skin health",
            "Ayurvedic superfood for overall wellness",
        ],
        howToUse: [
            "Add 1/2 teaspoon to warm milk (Golden Milk/Haldi Doodh)",
            "Use in curries, dal, rice, and vegetable dishes",
            "Mix with honey for face masks and wound healing",
            "Consume daily for anti-inflammatory benefits",
        ],
    },

    // ═══════════════════════════════════════════════════════════
    // A2 DAIRY
    // ═══════════════════════════════════════════════════════════
    {
        id: "milk-gir-1l",
        title: "Amrit Milk Organic A2 Gir Cow Milk - 1 L",
        price: "₹125",
        regularPrice: "₹140",
        image: "/assets/img/products/amrit_milk_gir_1l_v2.png",
        category: "Dairy",
        description:
            "Pure A2 beta-casein milk from indigenous Desi Gir cows. High nutritional value.",
        slug: "a2-gir-cow-milk-1l",
        sku: "AMRIT-DAIRY-001",
        subscription: true,
        highlights: [
            "100% pure A2 beta-casein protein",
            "From indigenous Desi Gir cows",
            "Farm-fresh daily delivery",
            "No hormones | No antibiotics | Grass-fed cows",
        ],
        ingredients: ["Pure A2 Gir Cow Milk (full-fat, unadulterated)"],
        benefits: [
            "Easier to digest than regular A1 milk",
            "Rich in calcium, protein, and essential vitamins",
            "Supports bone health, immunity, and growth",
            "Ideal for children, elderly, and lactose-sensitive individuals",
            "Traditional Ayurvedic superfood for vitality",
        ],
        howToUse: [
            "Boil and consume warm or at room temperature",
            "Use for making curd, paneer, ghee, or sweets",
            "Add to tea, coffee, or smoothies",
            "Best consumed fresh within 24 hours",
        ],
    },
    {
        id: "milk-sahiwal-1l",
        title: "Amrit Milk Organic A2 Sahiwal Cow Milk - 1 L",
        price: "₹100",
        image: "/assets/img/products/amrit_milk_sahiwal_1l_v2.png",
        category: "Dairy",
        description: "Fresh A2 milk from Sahiwal breed cows.",
        slug: "a2-sahiwal-cow-milk-1l",
        sku: "AMRIT-DAIRY-002",
        subscription: true,
        highlights: [
            "100% pure A2 beta-casein protein",
            "From indigenous Sahiwal breed cows",
            "Farm-fresh daily delivery",
            "No hormones | No antibiotics | Grass-fed cows",
        ],
        ingredients: ["Pure A2 Sahiwal Cow Milk (full-fat, unadulterated)"],
        benefits: [
            "Easier to digest than regular A1 milk",
            "Rich in calcium, protein, and essential vitamins",
            "Supports bone health, immunity, and growth",
            "Ideal for children, elderly, and lactose-sensitive individuals",
            "Traditional Ayurvedic superfood for vitality",
        ],
        howToUse: [
            "Boil and consume warm or at room temperature",
            "Use for making curd, paneer, ghee, or sweets",
            "Add to tea, coffee, or smoothies",
            "Best consumed fresh within 24 hours",
        ],
    },
    {
        id: "milk-buffalo-1l",
        title: "Amrit Milk Organic A2 Buffalo Milk - 1 L",
        price: "₹110",
        image: "/assets/img/products/amrit_milk_buffalo_1l_v2.png",
        category: "Dairy",
        description: "Rich and creamy A2 Buffalo milk.",
        slug: "a2-buffalo-milk-1l",
        sku: "AMRIT-DAIRY-003",
        subscription: true,
        highlights: [
            "100% pure A2 beta-casein protein from buffalo",
            "Higher fat content (7-8%) for rich, creamy texture",
            "Farm-fresh daily delivery",
            "No hormones | No antibiotics | Grass-fed buffalo",
        ],
        ingredients: ["Pure A2 Buffalo Milk (full-fat, unadulterated)"],
        benefits: [
            "Rich in calcium, phosphorus, and protein",
            "High in vitamins A, B12, and D",
            "Ideal for making thick curd, paneer, and ghee",
            "Supports bone density and muscle growth",
            "Perfect for traditional Indian sweets (kheer, rabri)",
        ],
        howToUse: [
            "Boil and consume warm for best digestion",
            "Use for making thick curd, paneer, and khoya",
            "Ideal for traditional sweets and desserts",
            "Best consumed fresh within 24 hours",
        ],
    },
    {
        id: "milk-colostrum-1l",
        title: "Amrit Milk Organic A2 Colostrum Milk - 1 L",
        price: "₹150",
        image: "/assets/img/products/amrit_milk_colostrum_1l_v2.png",
        category: "Dairy",
        description: "Immunity-boosting first milk (Colostrum) from A2 cows.",
        slug: "a2-colostrum-milk-1l",
        sku: "AMRIT-DAIRY-004",
        highlights: [
            "First milk (Colostrum) rich in antibodies",
            "From A2 Desi cows within 24-48 hours post-calving",
            "Thick, creamy, yellowish liquid gold",
            "No hormones | Naturally nutrient-dense",
        ],
        ingredients: ["Pure A2 Colostrum Milk (first milk from cows)"],
        benefits: [
            "Supercharges immunity with immunoglobulins (IgG)",
            "Rich in growth factors and lactoferrin",
            "Supports gut health and tissue repair",
            "Ideal for children, athletes, and recovery",
            "Traditional Ayurvedic remedy for strength and vitality",
        ],
        howToUse: [
            "Consume 50-100ml daily on empty stomach (dilute with warm water if needed)",
            "Boil gently to preserve nutrients",
            "Ideal for post-illness recovery and immunity boost",
            "Consult Ayurvedic practitioner for therapeutic use",
        ],
    },
    {
        id: "paneer-1kg",
        title: "Amrit Milk Organic Paneer - 1 kg",
        price: "₹500",
        image: "/assets/img/products/a2desicowmilkpaneer.png",
        category: "Dairy",
        description: "Freshly made Malai Paneer from A2 milk.",
        slug: "a2-paneer-1kg",
        sku: "AMRIT-DAIRY-006",
        highlights: [
            "Freshly made daily from A2 Desi Gir cow milk",
            "Soft, spongy texture with rich malai (cream)",
            "No preservatives | No additives",
            "Hand-crafted using traditional methods",
        ],
        ingredients: ["Pure A2 Cow Milk", "Natural curdling agent (lemon juice or vinegar)"],
        benefits: [
            "High in protein and calcium for muscle growth",
            "Rich source of conjugated linoleic acid (CLA)",
            "Supports bone health and weight management",
            "Ideal for vegetarians and fitness enthusiasts",
            "Pure, digestible protein source",
        ],
        howToUse: [
            "Use in curries (Paneer Butter Masala, Palak Paneer)",
            "Grill or shallow fry for tikkas and kebabs",
            "Add to salads, sandwiches, or wraps",
            "Consume fresh within 2-3 days (refrigerate)",
        ],
    },
    {
        id: "curd-1kg",
        title: "Amrit Milk Organic Curd - 1 kg",
        price: "₹200",
        image: "/assets/img/products/curd_new.png",
        category: "Dairy",
        description: "Thick, probiotic-rich Curd made from A2 milk.",
        slug: "a2-curd-1kg",
        sku: "AMRIT-DAIRY-007",

        highlights: [
            "Freshly made daily from A2 Desi Gir cow milk",
            "Thick, creamy texture with live probiotic cultures",
            "No preservatives | No additives | Hand-set",
            "Traditional clay-pot setting for authentic taste",
        ],
        ingredients: ["Pure A2 Cow Milk", "Live active cultures (Lactobacillus)"],
        benefits: [
            "Rich in probiotics for gut health and digestion",
            "High in protein, calcium, and B-vitamins",
            "Supports immunity and nutrient absorption",
            "Cooling effect for stomach and skin",
            "Ideal for weight management and metabolism",
        ],
        howToUse: [
            "Consume 1 bowl daily with meals or as a snack",
            "Use in raita, lassi, smoothies, or chaas",
            "Apply as a face mask for glowing skin",
            "Consume fresh within 2-3 days (refrigerate)",
        ],
    },
    {
        id: "khoya-1kg",
        title: "Amrit Milk Organic Khoya - 1 kg",
        price: "₹600",
        image: "/assets/img/products/amrit_khoya_1kg.png",
        category: "Dairy",
        description: "Pure milk solids (Khoya) for traditional sweets.",
        slug: "a2-khoya-1kg",
        sku: "AMRIT-DAIRY-008",
        highlights: [
            "Made from pure A2 Desi Gir cow milk",
            "Slow-cooked to perfection for rich flavor",
            "100% milk solids | No adulteration",
            "Hand-crafted using traditional methods",
        ],
        ingredients: ["Pure A2 Cow Milk (reduced to solids)"],
        benefits: [
            "Rich source of protein, calcium, and energy",
            "Contains all milk nutrients in concentrated form",
            "Ideal for traditional Indian sweets and desserts",
            "Supports muscle growth and bone health",
            "Pure, digestible, and highly nutritious",
        ],
        howToUse: [
            "Use for making gulab jamun, kalakand, barfi, and peda",
            "Add to halwa, kheer, and traditional sweets",
            "Cook with sugar and ghee for instant mithai",
            "Store in refrigerator, consume within 3-4 days",
        ],
    },

    // ═══════════════════════════════════════════════════════════
    // FLOUR (ATTA)
    // ═══════════════════════════════════════════════════════════
    {
        id: "atta-wheat-1kg",
        title: "Amrit Organic Whole Wheat Atta - 1 kg",
        price: "₹60",
        image: "/assets/img/products/amrit_atta_wheat_1kg.png",
        category: "Atta",
        description: "Stone-ground whole wheat flour.",
        slug: "whole-wheat-atta-1kg",
        sku: "AMRIT-ATTA-001",

        highlights: [
            "Stone-ground (chakki-ground) traditional method",
            "Retains bran, germ, and endosperm for nutrition",
            "Soft, fluffy rotis with authentic taste",
            "No maida | No preservatives | Fresh-ground",
        ],
        ingredients: ["Pure Organic Whole Wheat Grains (Triticum aestivum)"],
        benefits: [
            "Rich in dietary fiber for digestive health",
            "High in B-vitamins, iron, and magnesium",
            "Supports heart health and blood sugar control",
            "Provides sustained energy and satiety",
            "Ideal for daily rotis and parathas",
        ],
        howToUse: [
            "Knead with water to make soft dough",
            "Use for rotis, parathas, puris, naan",
            "Ideal for baking bread and healthy snacks",
            "Store in airtight container",
        ],
    },
    {
        id: "atta-multigrain-1kg",
        title: "Amrit Organic Multigrain Atta - 1 kg",
        price: "₹120",
        image: "/assets/img/products/amrit_atta_multigrain_1kg.png",
        category: "Atta",
        description: "Nutritious blend of multiple grains.",
        slug: "multigrain-atta-1kg",
        sku: "AMRIT-ATTA-002",
        highlights: [
            "Blend of Wheat, Kala Chana, Barley, Oats, Maize, Ragi",
            "Rich in fiber and protein",
            "Low glycemic index - diabetes friendly",
            "No preservatives | Fresh-ground",
        ],
        ingredients: [
            "Wheat (60%)",
            "Kala Chana (10%)",
            "Barley (10%)",
            "Oats (10%)",
            "Maize (5%)",
            "Ragi (5%)",
        ],
        benefits: [
            "Helps regulate blood sugar levels",
            "Aids weight management and digestion",
            "Rich in diverse nutrients and minerals",
            "Supports heart health",
            "Tasty and healthy alternative to regular atta",
        ],
        howToUse: [
            "Knead with warm water for soft rotis",
            "Use for rotis, parathas, cheela",
            "Ideal for health-conscious families",
            "Store in airtight container",
        ],
    },

    // ═══════════════════════════════════════════════════════════
    // LENTILS / DALS
    // ═══════════════════════════════════════════════════════════
    {
        id: "dal-toor-1kg",
        title: "Amrit Organic Toor / Arhar Dal - 1 kg",
        price: "₹180",
        image: "/assets/img/products/amrit_dal_toor.jpg",
        category: "Lentils/Dals",
        description: "Unpolished, farm-fresh Toor (Arhar) Dal.",
        slug: "organic-toor-dal-1kg",
        sku: "AMRIT-DAL-001",
        highlights: [
            "100% Unpolished and chemical-free",
            "Rich source of plant protein",
            "Farm-fresh and naturally aromatic",
            "No artificial colors or polish",
        ],
        ingredients: ["Pure Organic Toor Dal (Pigeon Peas)"],
        benefits: [
            "Excellent source of protein and folic acid",
            "Low glycemic index, good for diabetics",
            "Easily digestible and light on stomach",
            "Rich in dietary fiber and essential minerals",
            "Supports healthy metabolism",
        ],
        howToUse: [
            "Soak for 30 mins before cooking for best results",
            "Ideal for making Dal Tadka, Sambar, and Khichdi",
            "Cook with turmeric and mild spices",
            "Serve hot with rice or roti",
        ],
    },
    {
        id: "dal-chana-1kg",
        title: "Amrit Organic Chana Dal - 1 kg",
        price: "₹120",
        image: "/assets/img/products/dal_chana_premium.png?v=2",
        category: "Lentils/Dals",
        description: "Premium unpolished Chana Dal, rich in fiber.",
        slug: "organic-chana-dal-1kg",
        sku: "AMRIT-DAL-002",
        highlights: [
            "100% Organic and unpolished",
            "Nutty flavor and firm texture",
            "High in fiber and protein",
            "Chemical-free and pesticide-free",
        ],
        ingredients: ["Pure Organic Chana Dal (Split Chickpeas)"],
        benefits: [
            "High fiber content aids digestion",
            "Lowers cholesterol and supports heart health",
            "Provides sustained energy",
            "Rich in zinc and calcium",
            "Great for diabetic diet",
        ],
        howToUse: [
            "Soak for 1-2 hours before cooking",
            "Perfect for Dal Fry, Lauki Chana Dal, and Puran Poli",
            "Ground into Besan flour for snacks",
            "Add to vegetable curries for protein boost",
        ],
    },
    {
        id: "dal-urad-1kg",
        title: "Amrit Organic Urad Dal - 1 kg",
        price: "₹170",
        image: "/assets/img/products/amrit_dal_urad.jpg",
        category: "Lentils/Dals",
        description: "Whole Black Urad Dal for authentic Dal Makhani.",
        slug: "organic-urad-dal-1kg",
        sku: "AMRIT-DAL-003",
        highlights: [
            "Whole Black Urad with skin",
            "Rich, creamy texture when cooked",
            "Source of protein and iron",
            "Traditional stone-ground quality",
        ],
        ingredients: ["Pure Organic Black Urad Dal"],
        benefits: [
            "High protein content builds muscle",
            "Rich in magnesium and potassium for heart health",
            "Good for skin and hair health",
            "Boosts energy and vitality",
            "Supports bone health",
        ],
        howToUse: [
            "Soak overnight for Dal Makhani",
            "Use for making Idli/Dosa batter (after removing skin)",
            "Make traditional Urad Dal Tadka",
            "Cook slow for creamy texture",
        ],
    },
    {
        id: "dal-moong-1kg",
        title: "Amrit Organic Moong Dal - 1 kg",
        price: "₹160",
        image: "/assets/img/products/dal_moong_premium.png?v=2",
        category: "Lentils/Dals",
        description: "Yellow Split Moong Dal, easy to digest.",
        slug: "organic-moong-dal-1kg",
        sku: "AMRIT-DAL-004",
        highlights: [
            "Yellow split Moong beans",
            "Lightest and easiest to digest dal",
            "Quick cooking and versatile",
            "No polish | No chemicals",
        ],
        ingredients: ["Pure Organic Moong Dal (Split Green Gram)"],
        benefits: [
            "Ideal for convalescents and children",
            "Detoxifies the body (Ayurvedic favorite)",
            "Rich in antioxidants and vitamins",
            "Promotes weight loss and good digestion",
            "Cools the body",
        ],
        howToUse: [
            "Cooks quickly without soaking",
            "Perfect for Khichdi, Dal Fry, and soups",
            "Make Moong Dal Halwa/Sheera",
            "Ideal for light dinner",
        ],
    },

    {
        id: "atta-corn-1kg",
        title: "Amrit Organic Corn Flour - 1 kg",
        price: "₹120",
        image: "/assets/img/products/amrit_atta_corn_1kg.png",
        category: "Atta",
        description: "Pure yellow corn flour.",
        slug: "corn-flour-1kg",
        sku: "AMRIT-ATTA-003",
        highlights: [
            "100% pure yellow corn kernels",
            "Stone-ground for fine texture",
            "Naturally gluten-free flour",
            "Bright yellow color with sweet aroma",
        ],
        ingredients: ["Pure Yellow Corn Kernels (Zea mays)"],
        benefits: [
            "Gluten-free alternative for celiacs",
            "Rich in fiber and antioxidants",
            "Supports eye health (vitamin A)",
            "Ideal for baking and thickening",
            "Easy to digest",
        ],
        howToUse: [
            "Use for makki ki roti (corn flatbread)",
            "Add to baked goods for flavor and color",
            "Use as thickening agent in soups",
            "Mix with wheat for hybrid rotis",
        ],
    },
    {
        id: "atta-bajra-1kg",
        title: "Amrit Organic Bajra Flour - 1 kg",
        price: "₹120",
        image: "/assets/img/products/amrit_atta_bajra_1kg.png",
        category: "Atta",
        description: "Traditional pearl millet (Bajra) flour.",
        slug: "bajra-flour-1kg",
        sku: "AMRIT-ATTA-004",
        highlights: [
            "100% pure pearl millet (bajra) grains",
            "Traditional winter superfood",
            "Naturally gluten-free and warming",
            "Rajasthani heritage grain",
        ],
        ingredients: ["Pure Pearl Millet Grains (Pennisetum glaucum)"],
        benefits: [
            "Keeps body warm in winter months",
            "Rich in iron, magnesium, and protein",
            "Supports heart health and diabetes control",
            "High in fiber for digestion",
            "Boosts energy and stamina",
        ],
        howToUse: [
            "Make traditional bajra roti/bhakri",
            "Use in khichdi and porridge",
            "Mix with wheat for softer texture",
            "Best consumed in winter season",
        ],
    },
    {
        id: "atta-besan-1kg",
        title: "Amrit Organic Besan & Sattu - 1 kg",
        price: "₹200",
        image: "/assets/img/products/amrit_atta_besan_1kg.png",
        category: "Atta",
        description: "Pure Gram flour (Besan) and roasted gram flour (Sattu).",
        slug: "besan-sattu-1kg",
        sku: "AMRIT-ATTA-005",
        highlights: [
            "100% pure chickpea (chana) flour",
            "Fine texture with nutty aroma",
            "Naturally gluten-free and protein-rich",
            "Versatile for sweet and savory dishes",
        ],
        ingredients: ["Pure Chickpeas (Cicer arietinum)"],
        benefits: [
            "High in plant-based protein and fiber",
            "Supports muscle growth and satiety",
            "Good source of iron and folate",
            "Ideal for diabetics (low GI)",
            "Versatile for snacks and face packs",
        ],
        howToUse: [
            "Make pakoras, dhokla, and sev",
            "Use in ladoo, halwa, and sweets",
            "Mix with yogurt for face mask",
            "Add to smoothies for protein boost",
        ],
    },
    {
        id: "grains-millet-1kg",
        title: "Amrit Organic Millet Grains - 1 kg",
        price: "₹250",
        image: "/assets/img/products/amrit_grains_millet_1kg.png",
        category: "Atta",
        description: "Assorted ancient millet grains.",
        slug: "millet-grains-1kg",
        sku: "AMRIT-ATTA-006",
        highlights: [
            "Mix of foxtail, little, kodo, proso millets",
            "Ancient supergrains revived",
            "Naturally gluten-free and alkaline",
            "Climate-resilient heritage grains",
        ],
        ingredients: ["Foxtail, Little, Kodo, Proso, Barnyard Millets"],
        benefits: [
            "Rich in minerals, antioxidants, protein",
            "Supports heart health and weight loss",
            "Regulates blood sugar naturally",
            "Easily digestible superfood",
            "Eco-friendly sustainable grains",
        ],
        howToUse: [
            "Cook as rice substitute or khichdi",
            "Use in porridge, upma, and dosa",
            "Grind into flour for rotis",
            "Soak overnight, cook until fluffy",
        ],
    },

    // ═══════════════════════════════════════════════════════════
    // RICE
    // ═══════════════════════════════════════════════════════════
    {
        id: "rice-kala-jeera-1kg",
        title: "Amrit Organic Kala Jeera Rice - 1 kg",
        price: "₹100",
        image: "/assets/img/products/kala_jeera_rice.png",
        category: "Rice",
        description: "Aromatic small-grain Kala Jeera rice.",
        slug: "kala-jeera-rice-1kg",
        sku: "AMRIT-RICE-001",
        highlights: [
            "Aromatic small-grain black cumin rice",
            "Traditional variety from Terai region",
            "Fluffy texture with nutty flavor",
            "100% organic | Aged for 1 year",
        ],
        ingredients: ["Pure Organic Kala Jeera Rice (Oryza sativa)"],
        benefits: [
            "Low glycemic index for diabetics",
            "Rich in fiber and micronutrients",
            "Easy to digest compared to white rice",
            "Aromatic and flavorful",
            "Ideal for daily consumption",
        ],
        howToUse: [
            "Wash and soak for 20 minutes",
            "Cook with 1:2 rice-to-water ratio",
            "Perfect for biryani, pulao, and dal-chawal",
            "Store in airtight container",
        ],
    },
    {
        id: "rice-low-sugar-1kg",
        title: "Amrit Organic Kala Jeera Low-Sugar Rice - 1 kg",
        price: "₹120",
        image: "/assets/img/products/kala_jeera_rice.png",
        category: "Rice",
        description: "Diabetes-friendly low-sugar Kala Jeera rice.",
        slug: "kala-jeera-low-sugar-1kg",
        sku: "AMRIT-RICE-002",
        highlights: [
            "Specially processed for low glycemic index",
            "Diabetes-friendly rice variety",
            "Retains nutrients with low sugar release",
            "Doctor-recommended for diabetics",
        ],
        ingredients: ["Low-GI Kala Jeera Rice (processed)"],
        benefits: [
            "Minimal blood sugar spike after eating",
            "Rich in resistant starch",
            "Supports diabetes management",
            "High in fiber and minerals",
            "Suitable for weight management",
        ],
        howToUse: [
            "Wash, soak for 30 minutes before cooking",
            "Cook with 1:2.5 rice-to-water ratio",
            "Consume in moderation (controlled portions)",
            "Consult doctor for dietary guidance",
        ],
    },
    {
        id: "rice-basmati-1kg",
        title: "Amrit Organic Premium Basmati Rice - 1 kg",
        price: "₹185",
        image: "/assets/img/products/basmati_rice.png",
        category: "Rice",
        description: "Long-grain aged premium Basmati rice.",
        slug: "premium-basmati-rice-1kg",
        sku: "AMRIT-RICE-003",
        highlights: [
            "Extra-long grain premium basmati",
            "Aged for 2 years for aroma and texture",
            "Elongates 2x on cooking",
            "Traditional Pusa variety | Export quality",
        ],
        ingredients: ["Pure Organic Basmati Rice (Pusa 1121)"],
        benefits: [
            "Lower GI than regular white rice",
            "Rich aroma and delicate flavor",
            "Fluffy, non-sticky grains",
            "Premium quality for special occasions",
            "Easy to digest",
        ],
        howToUse: [
            "Wash, soak for 30 minutes",
            "Cook with 1:2 rice-to-water ratio",
            "Perfect for biryani, pulao, and jeera rice",
            "Fluff with fork after cooking",
        ],
    },
    {
        id: "rice-kala-namak-1kg",
        title: "Amrit Organic Kala Namak Rice - 1 kg",
        price: "₹350",
        image: "/assets/img/products/amrit_rice_kala_namak_1kg.png",
        category: "Rice",
        description: "Buddha's gift - highly aromatic and nutritious Kala Namak rice.",
        slug: "kala-namak-rice-1kg",
        sku: "AMRIT-RICE-004",
        highlights: [
            "Rare heritage rice variety (Buddha's gift)",
            "Intensely aromatic like pandan leaves",
            "Short, bold grains with black husk tip",
            "Premium artisanal rice | Limited harvest",
        ],
        ingredients: ["Pure Organic Kala Namak Rice (Siddharta cultivar)"],
        benefits: [
            "Rich in antioxidants and iron",
            "Unique aroma and  taste profile",
            "Heritage variety with cultural significance",
            "High nutritional value",
            "Sought after by gourmet chefs",
        ],
        howToUse: [
            "Wash gently, soak for 30-45 minutes",
            "Cook with 1:2.5 rice-to-water ratio",
            "Ideal for special occasions and festivals",
            "Best enjoyed plain to savor aroma",
        ],
    },

    // ═══════════════════════════════════════════════════════════
    // SWEETS & JAGGERY
    // ═══════════════════════════════════════════════════════════
    {
        id: "sweets-rasgulla",
        title: "Amrit Organic Rasgulla - 1 Jar",
        price: "₹450",
        image: "/assets/img/products/premium_rasgulla.png",
        category: "Sweets",
        description: "Soft and spongy Rasgullas made from A2 milk paneer.",
        slug: "rasgulla-jar",
        sku: "AMRIT-SWEET-001",
        highlights: [
            "Made from pure A2 Desi Gir cow milk paneer",
            "Soft, spongy, melt-in-mouth texture",
            "Soaked in light sugar syrup",
            "Traditional Bengali delicacy | Handcrafted",
        ],
        ingredients: ["A2 Cow Milk Paneer", "Sugar Syrup", "Cardamom"],
        benefits: [
            "High in protein and calcium",
            "Lighter than most Indian sweets",
            "Instant energy booster",
            "Perfect festive treat",
            "Made fresh with pure ingredients",
        ],
        howToUse: [
            "Serve chilled or at room temperature",
            "Consume within 3-4 days (refrigerate)",
            "Perfect for celebrations and festivals",
            "Pair with rabri or ice cream for fusion dessert",
        ],
    },
    {
        id: "jaggery-bites-500g",
        title: "Amrit Organic Jaggery Bites (Desi Chocolate Style) - 500g",
        price: "₹110",
        image: "/assets/img/products/premium_jaggery_bites.png",
        category: "Sweets",
        description: "Healthy jaggery bites, a natural substitute for chocolates.",
        slug: "jaggery-bites-500g",
        sku: "AMRIT-SWEET-002",
        highlights: [
            "Healthy alternative to commercial chocolates",
            "Bite-sized jaggery cubes",
            "No added sugar or chemicals",
            "Kids love these natural treats",
        ],
        ingredients: ["Pure Organic Jaggery (Gur)"],
        benefits: [
            "Natural iron and mineral boost",
            "Healthier than refined sugar treats",
            "Aids digestion and metabolism",
            "Satisfies sweet cravings naturally",
            "Good source of instant energy",
        ],
        howToUse: [
            "Enjoy 2-3 bites as a healthy snack",
            "Perfect for kids' lunchboxes",
            "Consume post-meals for digestion",
            "Store in cool, dry place",
        ],
    },
    {
        id: "jaggery-1kg",
        title: "Amrit Organic Jaggery - 1 kg",
        price: "₹150",
        image: "/assets/img/products/premium_jaggery_bites.png",
        category: "Sweets",
        description: "Pure chemical-free Organic Jaggery.",
        slug: "jaggery-1kg-pure",
        sku: "AMRIT-SWEET-003",
        highlights: [
            "100% pure sugarcane jaggery (gur)",
            "Traditional open-pan boiling method",
            "No chemicals | No preservatives",
            "Rich golden-brown color with earthy aroma",
        ],
        ingredients: ["Pure Organic Sugarcane Juice"],
        benefits: [
            "Rich source of iron and minerals",
            "Aids digestion and detoxification",
            "Boosts immunity and hemoglobin",
            "Healthier alternative to white sugar",
            "Ayurvedic superfood for winters",
        ],
        howToUse: [
            "Use as natural sweetener in tea, milk, desserts",
            "Make traditional sweets like chikki and ladoo",
            "Consume small piece post-meals for digestion",
            "Store in airtight container",
        ],
    },

    // ═══════════════════════════════════════════════════════════
    // WELLNESS / PERSONAL CARE
    // ═══════════════════════════════════════════════════════════
    {
        id: "lip-balm",
        title: "Amrit Organic Lip Balm (Moisturizer)",
        price: "₹300",
        image: "/assets/img/products/amrit_lip_balm.png",
        category: "Wellness",
        description: "Natural moisturizing Lip Balm.",
        slug: "lip-balm-moisturizer",
        sku: "AMRIT-WELL-001",
        highlights: [
            "100% natural and chemical-free formula",
            "Deeply moisturizes and heals chapped lips",
            "Long-lasting protection",
            "Compact stick for on-the-go use",
        ],
        ingredients: ["Beeswax", "Coconut Oil", "Shea Butter", "Vitamin E", "Natural Flavor"],
        benefits: [
            "Heals dry, cracked, and chapped lips",
            "Provides SPF-like natural sun protection",
            "Non-sticky, lightweight formula",
            "Suitable for all skin types",
            "Safe for daily use",
        ],
        howToUse: [
            "Apply generously on lips as needed",
            "Use before going outdoors for sun protection",
            "Apply at night for overnight healing",
            "Reapply after eating or drinking",
        ],
    },
    {
        id: "bees-wax",
        title: "Amrit Organic Bees Wax (Moisturizer)",
        price: "₹500",
        image: "/assets/img/products/amrit_bees_wax.png",
        category: "Wellness",
        description: "Pure Bees Wax for skin hydration.",
        slug: "bees-wax-moisturizer",
        sku: "AMRIT-WELL-002",
        highlights: [
            "100% pure, raw beeswax from organic hives",
            "Multi-purpose beauty and skincare ingredient",
            "Natural golden color with honey aroma",
            "Chemical-free | Unrefined | Handcrafted",
        ],
        ingredients: ["Pure Organic Beeswax"],
        benefits: [
            "Natural emollient for deep skin hydration",
            "Forms protective barrier on skin",
            "Anti-inflammatory and antibacterial",
            "Ideal for DIY skincare and lip balms",
            "Soothes eczema and dry skin",
        ],
        howToUse: [
            "Melt and mix with carrier oils for balms",
            "Use in DIY lotions, creams, and salves",
            "Apply on dry elbows, heels, and cuticles",
            "Store in cool, dry place away from heat",
        ],
    },
    {
        id: "bull-balm-rollon",
        title: "Amrit Organic Bull Balm Roll-On (10ml)",
        price: "₹225",
        image: "/assets/img/products/amrit_bull_balm_rollon.png",
        category: "Wellness",
        description: "Ancient formula for pain relief in a handy roll-on.",
        slug: "bull-balm-rollon",
        sku: "AMRIT-WELL-003",
        highlights: [
            "Powerful blend of natural oils",
            "Smooth roll-on application",
            "Instant cooling + warming relief",
            "Travel-friendly | Non-sticky | Farm-crafted",
        ],
        ingredients: [
            "Base Oil (Nourishing + Lubricating)",
            "Menthol Essence",
            "Tulsi Oil",
            "Lemongrass Oil",
            "Eucalyptus Oil",
            "Kapoor Extract",
        ],
        benefits: [
            "Relieves body pain, stiffness, muscle tension",
            "Helps with cold, congestion, blocked nose",
            "Useful for bruises & minor injuries",
            "Ideal for massage therapy",
            "Provides refreshment & rejuvenation when inhaled",
        ],
        howToUse: [
            "Roll on the affected area",
            "Massage gently for 20-30 seconds",
            "For cold relief – inhale lightly OR apply on chest/neck",
            "Apply on temples/behind ears for instant freshness",
        ],
    },
    {
        id: "bull-balm-spray",
        title: "Amrit Organic Bull Balm Spray (10ml)",
        price: "₹250",
        image: "/assets/img/products/premium_bull_balm_v3.png",
        category: "Wellness",
        description: "Targeted pain relief spray.",
        slug: "bull-balm-spray",
        sku: "AMRIT-WELL-004",
        highlights: [
            "Powerful blend of natural oils",
            "Convenient spray application",
            "Instant cooling + warming relief",
            "Travel-friendly | Quick-dry | Farm-crafted",
        ],
        ingredients: [
            "Base Oil (Nourishing + Lubricating)",
            "Menthol Essence",
            "Tulsi Oil",
            "Lemongrass Oil",
            "Eucalyptus Oil",
            "Kapoor Extract",
        ],
        benefits: [
            "Relieves body pain, stiffness, muscle tension",
            "Helps with cold, congestion, blocked nose",
            "Useful for bruises & minor injuries",
            "Ideal for targeted relief",
            "Provides refreshment & rejuvenation when inhaled",
        ],
        howToUse: [
            "Spray on the affected area from 6 inches away",
            "Massage gently for 20-30 seconds",
            "For cold relief – spray lightly on chest/neck",
            "Spray on temples for instant freshness",
        ],
    },
    {
        id: "bull-balm-dropper",
        title: "Amrit Organic Bull Balm Dropper (10ml)",
        price: "₹290",
        image: "/assets/img/products/premium_bull_balm_v3.png",
        category: "Wellness",
        description: "Concentrated formula for deep tissue relief.",
        slug: "bull-balm-dropper",
        sku: "AMRIT-WELL-005",
        highlights: [
            "Powerful blend of natural oils",
            "Precise dropper application",
            "Concentrated formula for deep relief",
            "Travel-friendly | Controlled dosing | Farm-crafted",
        ],
        ingredients: [
            "Base Oil (Nourishing + Lubricating)",
            "Menthol Essence",
            "Tulsi Oil",
            "Lemongrass Oil",
            "Eucalyptus Oil",
            "Kapoor Extract",
        ],
        benefits: [
            "Relieves body pain, stiffness, muscle tension",
            "Helps with cold, congestion, blocked nose",
            "Useful for bruises & minor injuries",
            "Ideal for deep tissue massage therapy",
            "Provides refreshment & rejuvenation when inhaled",
        ],
        howToUse: [
            "Apply 2-3 drops on the affected area",
            "Massage deeply for 30-60 seconds",
            "For cold relief – apply drops on chest/neck, inhale vapors",
            "Apply 1 drop on temples for instant freshness",
        ],
    },

    // ═══════════════════════════════════════════════════════════
    // COW-BASED (GAU SEVA)
    // ═══════════════════════════════════════════════════════════
    {
        id: "cow-manure-1kg",
        title: "Amrit Organic Cow Manure - 1 kg",
        price: "₹30",
        image: "/assets/img/products/cow_manure.png",
        category: "Gau Seva",
        description: "Organic manure from Desi Gir cows for your garden.",
        slug: "cow-manure-1kg",
        sku: "AMRIT-GAU-001",
        highlights: [
            "100% organic from grass-fed Desi Gir cows",
            "Naturally composted and aged",
            "Rich in NPK and beneficial microbes",
            "Eco-friendly | Chemical-free fertilizer",
        ],
        ingredients: ["Pure Organic Cow Dung (composted)"],
        benefits: [
            "Enriches soil with organic matter and nutrients",
            "Improves soil structure and water retention",
            "Promotes healthy plant growth naturally",
            "Sustainable alternative to chemical fertilizers",
            "Supports beneficial soil microorganisms",
        ],
        howToUse: [
            "Mix with soil before planting (1:3 ratio)",
            "Use as top dressing for potted plants",
            "Prepare liquid manure by soaking in water",
            "Apply every 2-3 weeks for best results",
        ],
    },
    {
        id: "cow-dung-cakes-2pcs",
        title: "Amrit Organic Upla (Cow Dung Cakes) - 2 pcs",
        price: "₹100",
        image: "/assets/img/products/amrit_cow_dung_upla.png",
        category: "Gau Seva",
        description: "Traditionally dried Cow Dung cakes for rituals and fuel.",
        slug: "cow-dung-cakes-2pcs",
        sku: "AMRIT-GAU-002",
        highlights: [
            "Hand-crafted from Desi Gir cow dung",
            "Sun-dried naturally for weeks",
            "Traditional fuel and ritual use",
            "Sacred in Vedic traditions | Eco-friendly",
        ],
        ingredients: ["Pure Organic Cow Dung (sun-dried)"],
        benefits: [
            "Used in traditional havans and yajnas",
            "Purifies air when burned (removes toxins)",
            "Eco-friendly biomass fuel",
            "Repels mosquitoes and insects naturally",
            "Part of Gau Seva (service to cows)",
        ],
        howToUse: [
            "Use in havans, pujas, and religious ceremonies",
            "Burn slowly for air purification",
            "Place in corners to repel insects",
            "Store in dry place away from moisture",
        ],
    },
    {
        id: "gaumutra-1l",
        title: "Amrit Organic Gaumutra - 1 L",
        price: "₹100",
        image: "/assets/img/products/premium_cow_based_products.png",
        category: "Gau Seva",
        description: "Distilled Gaumutra for spiritual and medicinal use.",
        slug: "gaumutra-1l",
        sku: "AMRIT-GAU-003",
        highlights: [
            "From Desi Gir cows (grass-fed, hormone-free)",
            "Filtered and distilled for purity",
            "Traditional Ayurvedic ingredient",
            "Spiritual purification use",
        ],
        ingredients: ["Pure Organic Cow Urine (distilled)"],
        benefits: [
            "Used in Ayurvedic medicine preparations",
            "Natural pesticide for organic farming",
            "Purification in spiritual rituals",
            "Supports plant growth (diluted as fertilizer)",
            "Traditional remedy in Panchagavya therapy",
        ],
        howToUse: [
            "Dilute 1:10 with water for plant spray (pest control)",
            "Use in Ayurvedic preparations as directed",
            "Consult Ayurvedic practitioner for medicinal use",
            "Store in cool, dark place",
        ],
    },

    // ═══════════════════════════════════════════════════════════
    // COMBO PACKS (Value Bundles - Ghee, Honey & Essential Oils)
    // ═══════════════════════════════════════════════════════════
    {
        id: "combo-wellness-trio",
        title: "Wellness Trio Pack",
        price: "₹3,500",
        regularPrice: "₹3,900",
        image: "/assets/img/products/combo_wellness_trio_v6.png",
        category: "Combos",
        description:
            "1kg A2 Ghee + 1kg Multiflora Honey + 10ml Tulsi Oil. The ultimate Ayurvedic wellness bundle.",
        slug: "wellness-trio-pack",
        sku: "AMRIT-COMBO-001",
        featured: true,
        badge: "Best Value",
        highlights: [
            "Complete Ayurvedic wellness trio",
            "Save ₹400 compared to individual prices",
            "Premium A2 Bilona Ghee + Raw Forest Honey + Pure Tulsi Oil",
            "Perfect for health-conscious families",
        ],
        benefits: [
            "Ghee: Strengthens immunity, promotes digestion",
            "Honey: Natural energy booster, antioxidant-rich",
            "Tulsi Oil: Stress relief, respiratory health",
            "All products are 100% organic and chemical-free",
        ],
    },
    {
        id: "combo-immunity-booster",
        title: "Immunity Booster Pack",
        price: "₹2,600",
        regularPrice: "₹2,900",
        image: "/assets/img/products/combo_immunity_booster_v5.png",
        category: "Combos",
        description:
            "1kg Multiflora Honey + 10ml Tulsi Oil + 10ml Mint Oil. Natural immunity power combo.",
        slug: "immunity-booster-pack",
        sku: "AMRIT-COMBO-002",
        featured: true,
        badge: "Immunity Shield",
        highlights: [
            "Powerful immunity-boosting trio",
            "Save ₹300 compared to individual prices",
            "Raw Honey + Tulsi + Mint essential oils",
            "Fight cold, cough & respiratory issues naturally",
        ],
        benefits: [
            "Honey: Natural antimicrobial, soothes throat",
            "Tulsi Oil: Adaptogenic, clears congestion",
            "Mint Oil: Cooling relief, headache remedy",
            "Perfect for monsoon & winter seasons",
        ],
    },
    {
        id: "combo-aromatherapy",
        title: "Aromatherapy Essentials",
        price: "₹850",
        regularPrice: "₹950",
        image: "/assets/img/products/combo_aromatherapy_v6.png",
        category: "Combos",
        description:
            "10ml Tulsi Oil + 10ml Lemongrass Oil + 10ml Mint Oil. Complete aromatherapy set for wellness.",
        slug: "aromatherapy-essentials",
        sku: "AMRIT-COMBO-003",
        badge: "Aromatherapy Kit",
        highlights: [
            "Complete essential oils set",
            "Save ₹100 compared to individual prices",
            "Perfect for diffusers & massage therapy",
            "100% pure steam-distilled oils",
        ],
        benefits: [
            "Tulsi: Stress relief, mental clarity",
            "Lemongrass: Mood booster, insect repellent",
            "Mint: Refreshing, headache relief",
            "Ideal for home wellness routines",
        ],
    },
    {
        id: "combo-golden-healing",
        title: "Golden Healing Duo",
        price: "₹3,600",
        regularPrice: "₹3,900",
        image: "/assets/img/products/combo_golden_healing_v5.png",
        category: "Combos",
        description:
            "1kg A2 Ghee + 1kg Jamun Honey. The golden Ayurvedic healing pair for digestion & immunity.",
        slug: "golden-healing-duo",
        sku: "AMRIT-COMBO-004",
        badge: "Ayurvedic Gold",
        highlights: [
            "Traditional Ayurvedic healing duo",
            "Save ₹300 compared to individual prices",
            "Pure Bilona Ghee + Diabetic-friendly Jamun Honey",
            "Perfect for golden milk (Haldi Doodh)",
        ],
        benefits: [
            "Ghee: Enhances digestion & nutrient absorption",
            "Jamun Honey: Low GI, diabetes-friendly",
            "Combined anti-inflammatory properties",
            "Supports gut health & metabolism",
        ],
    },
    {
        id: "combo-complete-care",
        title: "Complete Care Pack",
        price: "₹4,200",
        regularPrice: "₹4,650",
        image: "/assets/img/products/combo_complete_care_v5.png",
        category: "Combos",
        description:
            "1kg A2 Ghee + 1kg Honey + 10ml Tulsi + 10ml Lemongrass + 10ml Mint Oil. Ultimate wellness bundle.",
        slug: "complete-care-pack",
        sku: "AMRIT-COMBO-005",
        featured: true,
        badge: "Ultimate Bundle",
        highlights: [
            "Everything you need for complete wellness",
            "Save ₹450 compared to individual prices",
            "5 premium products in one bundle",
            "Perfect gift for health-conscious loved ones",
        ],
        benefits: [
            "Ghee + Honey: Core immunity & energy",
            "Tulsi + Mint: Respiratory & stress support",
            "Lemongrass: Mood & skincare",
            "Complete family wellness solution",
        ],
    },
    {
        id: "combo-panchamrit-custom",
        title: "Panchamrit Custom Combo",
        price: "₹3,900", // Base price estimate
        regularPrice: "₹4,500",
        image: "/assets/img/products/panchamrit_combo.jpg",
        category: "Combos",
        description:
            "Build your own Panchamrit bundle. Choose your A2 Ghee, Oils, Honey, Grains, and extras.",
        slug: "panchamrit-custom-combo",
        sku: "AMRIT-COMBO-006",
        featured: true,
        badge: "Customizable",
        highlights: [
            "Fully customizable wellness bundle",
            "Select your preferred Ghee, Oils, Honey & Grains",
            "Includes options for Jaggery & Sirka",
            "Perfect for gifting or monthly groceries",
        ],
        benefits: [
            "Tailored to your family's needs",
            "All organic and chemical-free products",
            "Save with bundle pricing",
            "Complete kitchen solution",
        ],
    },
];

export const categories = [
    { id: "all", label: "All Products", icon: "LayoutGrid" },
    { id: "combos", label: "Combo Packs", icon: "Gift" },
    { id: "vedic-essentials", label: "Ghee & Vedic Essentials", icon: "Utensils" }, // Ghee + Honey
    { id: "cold-pressed-oils", label: "Cold-Pressed Oils", icon: "Droplet" },
    { id: "essential-oils", label: "Essential Oils", icon: "Sparkles" },
    { id: "honey", label: "Raw Honey", icon: "Hexagon" },
    { id: "dairy", label: "A2 Dairy", icon: "Milk" },
    { id: "atta", label: "Wheats & Flours", icon: "Wheat" },
    { id: "rice", label: "Rice & Grains", icon: "Leaf" },
    { id: "wellness", label: "Wellness", icon: "Package" },
] as const;
