export const products = [
    // ═══════════════════════════════════════════════════════════
    // A2 DAIRY
    // ═══════════════════════════════════════════════════════════
    {
        id: "milk-gir-1l",
        title: "A2 Gir cow milk - 1 L",
        price: "₹125",
        regularPrice: "₹140",
        image: "/assets/img/products/a2milkbottles-gircowandsahiwalcowmilkbottles.png",
        category: "Dairy",
        description:
            "Pure A2 beta-casein milk from indigenous Desi Gir cows. High nutritional value.",
        slug: "a2-gir-cow-milk-1l",
        sku: "AMRIT-DAIRY-001",
        subscription: true,
    },
    {
        id: "milk-sahiwal-1l",
        title: "A2 Sahiwal cow milk - 1 L",
        price: "₹95",
        image: "/assets/img/products/a2milkbottles-gircowandsahiwalcowmilkbottles.png",
        category: "Dairy",
        description: "Fresh A2 milk from Sahiwal breed cows.",
        slug: "a2-sahiwal-cow-milk-1l",
        sku: "AMRIT-DAIRY-002",
        subscription: true,
    },
    {
        id: "milk-buffalo-1l",
        title: "A2 Buffalo Milk - 1 L",
        price: "₹110",
        image: "/assets/img/products/a2buffalomilkanda2colostrummilk.png",
        category: "Dairy",
        description: "Rich and creamy A2 Buffalo milk.",
        slug: "a2-buffalo-milk-1l",
        sku: "AMRIT-DAIRY-003",
        subscription: true,
    },
    {
        id: "milk-colostrum-1l",
        title: "A2 Colostrum Milk - 1 L",
        price: "₹150",
        image: "/assets/img/products/a2buffalomilkanda2colostrummilk.png",
        category: "Dairy",
        description: "Immunity-boosting first milk (Colostrum) from A2 cows.",
        slug: "a2-colostrum-milk-1l",
        sku: "AMRIT-DAIRY-004",
    },
    {
        id: "ghee-cow-1kg",
        title: "A2 Cow Ghee - 1 kg",
        price: "₹2500",
        image: "/assets/img/products/a2desicowgheeglassjarbilonamethod.png",
        category: "Dairy",
        description: "Traditional Bilona method A2 Cow Ghee. Pure gold for health.",
        slug: "a2-cow-ghee-1kg",
        sku: "AMRIT-DAIRY-005",
        featured: true,
        badge: "Pure Vedic",
    },
    {
        id: "paneer-1kg",
        title: "Paneer - 1 kg",
        price: "₹500",
        image: "/assets/img/products/a2desicowmilkpaneer.png",
        category: "Dairy",
        description: "Freshly made Malai Paneer from A2 milk.",
        slug: "a2-paneer-1kg",
        sku: "AMRIT-DAIRY-006",
    },
    {
        id: "curd-1kg",
        title: "Curd - 1 kg",
        price: "₹200",
        image: "/assets/img/products/a2desicowmilkcurd.png",
        category: "Dairy",
        description: "Thick, probiotic-rich Curd made from A2 milk.",
        slug: "a2-curd-1kg",
        sku: "AMRIT-DAIRY-007",
        subscription: true,
    },
    {
        id: "khoya-1kg",
        title: "Khoya - 1 kg",
        price: "₹600",
        image: "/assets/img/sweets.png",
        category: "Dairy",
        description: "Pure milk solids (Khoya) for traditional sweets.",
        slug: "a2-khoya-1kg",
        sku: "AMRIT-DAIRY-008",
    },

    // ═══════════════════════════════════════════════════════════
    // FLOUR (ATTA)
    // ═══════════════════════════════════════════════════════════
    {
        id: "atta-wheat-1kg",
        title: "Whole Wheat Atta - 1 kg",
        price: "₹60",
        image: "/assets/img/generated/wheat-atta.png",
        category: "Atta",
        description: "Stone-ground whole wheat flour.",
        slug: "whole-wheat-atta-1kg",
        sku: "AMRIT-ATTA-001",
        subscription: true,
    },
    {
        id: "atta-multigrain-1kg",
        title: "Multi grain - 1 kg",
        price: "₹120",
        image: "/assets/img/generated/multigrain-atta.png",
        category: "Atta",
        description: "Nutritious blend of multiple grains.",
        slug: "multigrain-atta-1kg",
        sku: "AMRIT-ATTA-002",
    },
    {
        id: "atta-corn-1kg",
        title: "Corn Flour - 1 kg",
        price: "₹120",
        image: "/assets/img/products/cornflour.png",
        category: "Atta",
        description: "Pure yellow corn flour.",
        slug: "corn-flour-1kg",
        sku: "AMRIT-ATTA-003",
    },
    {
        id: "atta-bajra-1kg",
        title: "Bajra - 1 kg",
        price: "₹120",
        image: "/assets/img/products/bajraflour.png",
        category: "Atta",
        description: "Traditional pearl millet (Bajra) flour.",
        slug: "bajra-flour-1kg",
        sku: "AMRIT-ATTA-004",
    },
    {
        id: "atta-besan-1kg",
        title: "Besan, Sattu - 1 kg",
        price: "₹200",
        image: "/assets/img/generated/besan-flour.png",
        category: "Atta",
        description: "Pure Gram flour (Besan) and roasted gram flour (Sattu).",
        slug: "besan-sattu-1kg",
        sku: "AMRIT-ATTA-005",
    },
    {
        id: "grains-millet-1kg",
        title: "Millet Grains - 1 kg",
        price: "₹250",
        image: "/assets/img/millet-mix.png",
        category: "Atta",
        description: "Assorted ancient millet grains.",
        slug: "millet-grains-1kg",
        sku: "AMRIT-ATTA-006",
    },

    // ═══════════════════════════════════════════════════════════
    // RICE
    // ═══════════════════════════════════════════════════════════
    {
        id: "rice-kala-jeera-1kg",
        title: "Kala Jeera Rice - 1 kg",
        price: "₹100",
        image: "/assets/img/generated/kala-jeera-rice.png",
        category: "Rice",
        description: "Aromatic small-grain Kala Jeera rice.",
        slug: "kala-jeera-rice-1kg",
        sku: "AMRIT-RICE-001",
    },
    {
        id: "rice-low-sugar-1kg",
        title: "Kala Jeera Low-Sugar - 1 kg",
        price: "₹120",
        image: "/assets/img/generated/low-sugar-rice.png",
        category: "Rice",
        description: "Diabetes-friendly low-sugar Kala Jeera rice.",
        slug: "kala-jeera-low-sugar-1kg",
        sku: "AMRIT-RICE-002",
    },
    {
        id: "rice-basmati-1kg",
        title: "Premium Basmati - 1 kg",
        price: "₹185",
        image: "/assets/img/generated/basmati-rice.png",
        category: "Rice",
        description: "Long-grain aged premium Basmati rice.",
        slug: "premium-basmati-rice-1kg",
        sku: "AMRIT-RICE-003",
    },
    {
        id: "rice-kala-namak-1kg",
        title: "Kala Namak Rice - 1 kg",
        price: "₹350",
        image: "/assets/img/generated/kala-namak-rice.png",
        category: "Rice",
        description: "Buddha's gift - highly aromatic and nutritious Kala Namak rice.",
        slug: "kala-namak-rice-1kg",
        sku: "AMRIT-RICE-004",
    },

    // ═══════════════════════════════════════════════════════════
    // COLD-PRESSED OILS
    // ═══════════════════════════════════════════════════════════
    {
        id: "oil-yellow-mustard-1l",
        title: "Yellow Mustard Oil - 1 L",
        price: "₹380",
        image: "/assets/img/generated/yellow-mustard-oil.png",
        category: "Oils",
        description: "Cold-pressed Yellow Mustard oil (Kacchi Ghani).",
        slug: "yellow-mustard-oil-1l",
        sku: "AMRIT-OIL-001",
        featured: true,
    },
    {
        id: "oil-black-mustard-1l",
        title: "Black Mustard Oil - 1 L",
        price: "₹350",
        image: "/assets/img/generated/black-mustard-oil.png",
        category: "Oils",
        description: "Cold-pressed Black Mustard oil, pungent and pure.",
        slug: "black-mustard-oil-1l",
        sku: "AMRIT-OIL-002",
        featured: true,
    },
    {
        id: "oil-groundnut-1l",
        title: "Groundnut Oil - 1 L",
        price: "₹600",
        image: "/assets/img/products/peanut oil.png",
        category: "Oils",
        description: "Cold-pressed Groundnut oil, rich in flavor.",
        slug: "groundnut-oil-1l-premium",
        sku: "AMRIT-OIL-003",
        featured: true,
    },
    {
        id: "oil-coconut-1l",
        title: "Coconut Oil - 1 L",
        price: "₹1000",
        image: "/assets/img/generated/coconut-oil.png",
        category: "Oils",
        description: "Pure cold-pressed Coconut oil for cooking and care.",
        slug: "coconut-oil-1l-premium",
        sku: "AMRIT-OIL-004",
        featured: true,
    },
    {
        id: "oil-sesame-1l",
        title: "Sesame (Til) Oil - 1 L",
        price: "₹800",
        image: "/assets/img/generated/sesame-oil.png",
        category: "Oils",
        description: "Cold-pressed Sesame (Til) oil.",
        slug: "sesame-til-oil-1l",
        sku: "AMRIT-OIL-005",
        featured: true,
    },
    {
        id: "oil-tulsi-10ml",
        title: "Tulsi Oil - 10 ml",
        price: "₹300",
        image: "/assets/img/tulsi-oil.png",
        category: "Oils",
        description: "Sacred Tulsi essential oil.",
        slug: "tulsi-oil-10ml",
        sku: "AMRIT-OIL-006",
        featured: true,
    },
    {
        id: "oil-lemongrass-10ml",
        title: "Lemongrass Oil - 10 ml",
        price: "₹400",
        image: "/assets/img/lemongrass-oil.png",
        category: "Oils",
        description: "Refreshing Lemongrass essential oil.",
        slug: "lemongrass-oil-10ml",
        sku: "AMRIT-OIL-007",
        featured: true,
    },
    {
        id: "oil-menthol-10ml",
        title: "Menthol Oil - 10 ml",
        price: "₹250",
        image: "/assets/img/mentha-oil.png",
        category: "Oils",
        description: "Cooling Menthol essential oil.",
        slug: "menthol-oil-10ml",
        sku: "AMRIT-OIL-008",
        featured: true,
    },

    // ═══════════════════════════════════════════════════════════
    // SWEETS & JAGGERY
    // ═══════════════════════════════════════════════════════════
    {
        id: "sweets-rasgulla",
        title: "Rasgulla - 1 Jar",
        price: "₹450",
        image: "/assets/img/sweets.png",
        category: "Sweets",
        description: "Soft and spongy Rasgullas made from A2 milk paneer.",
        slug: "rasgulla-jar",
        sku: "AMRIT-SWEET-001",
    },
    {
        id: "jaggery-bites-500g",
        title: "Jaggery Bites (Desi Chocolate Style) - 500g",
        price: "₹110",
        image: "/assets/img/jaggery.png",
        category: "Sweets",
        description: "Healthy jaggery bites, a natural substitute for chocolates.",
        slug: "jaggery-bites-500g",
        sku: "AMRIT-SWEET-002",
    },
    {
        id: "jaggery-1kg",
        title: "Jaggery - 1 kg",
        price: "₹150",
        image: "/assets/img/jaggery.png",
        category: "Sweets",
        description: "Pure chemical-free Organic Jaggery.",
        slug: "jaggery-1kg-pure",
        sku: "AMRIT-SWEET-003",
    },

    // ═══════════════════════════════════════════════════════════
    // WELLNESS / PERSONAL CARE
    // ═══════════════════════════════════════════════════════════
    {
        id: "lip-balm",
        title: "Lip Balm (Moisturizer)",
        price: "₹300",
        image: "/assets/img/balm.png",
        category: "Wellness",
        description: "Natural moisturizing Lip Balm.",
        slug: "lip-balm-moisturizer",
        sku: "AMRIT-WELL-001",
    },
    {
        id: "bees-wax",
        title: "Bees Wax (Moisturizer)",
        price: "₹500",
        image: "/assets/img/balm.png",
        category: "Wellness",
        description: "Pure Bees Wax for skin hydration.",
        slug: "bees-wax-moisturizer",
        sku: "AMRIT-WELL-002",
    },
    {
        id: "bull-balm-rollon",
        title: "Bull Balm Roll-On (10ml)",
        price: "₹225",
        image: "/assets/img/balm.png",
        category: "Wellness",
        description: "Ancient formula for pain relief in a handy roll-on.",
        slug: "bull-balm-rollon",
        sku: "AMRIT-WELL-003",
    },
    {
        id: "bull-balm-spray",
        title: "Bull Balm Spray (10ml)",
        price: "₹250",
        image: "/assets/img/balm.png",
        category: "Wellness",
        description: "Targeted pain relief spray.",
        slug: "bull-balm-spray",
        sku: "AMRIT-WELL-004",
    },
    {
        id: "bull-balm-dropper",
        title: "Bull Balm Dropper (10ml)",
        price: "₹290",
        image: "/assets/img/balm.png",
        category: "Wellness",
        description: "Concentrated formula for deep tissue relief.",
        slug: "bull-balm-dropper",
        sku: "AMRIT-WELL-005",
    },

    // ═══════════════════════════════════════════════════════════
    // HONEY
    // ═══════════════════════════════════════════════════════════
    {
        id: "honey-multiflora-1kg",
        title: "Multiflora Honey - 1 kg",
        price: "₹1200",
        image: "/assets/img/generated/multiflora-honey.png",
        category: "Honey",
        description: "Pure Multiflora honey collected from diverse forest flowers.",
        slug: "multiflora-honey-1kg",
        sku: "AMRIT-HONEY-001",
        featured: true,
        badge: "Raw & Pure",
    },
    {
        id: "honey-jamun-1kg",
        title: "Jamun Honey - 1 kg",
        price: "₹1200",
        image: "/assets/img/generated/jamun-honey.png",
        category: "Honey",
        description: "Medicinal honey from Jamun flower nectar. Good for diabetics.",
        slug: "jamun-honey-1kg",
        sku: "AMRIT-HONEY-002",
        featured: true,
    },

    // ═══════════════════════════════════════════════════════════
    // OTHER PRODUCTS
    // ═══════════════════════════════════════════════════════════
    {
        id: "turmeric-1kg",
        title: "Organic Turmeric - 1 kg",
        price: "₹900",
        image: "/assets/img/turmeric.png",
        category: "Other",
        description: "High-curcumin Organic Turmeric powder.",
        slug: "organic-turmeric-1kg",
        sku: "AMRIT-MISC-001",
    },

    // ═══════════════════════════════════════════════════════════
    // COW-BASED (GAU SEVA)
    // ═══════════════════════════════════════════════════════════
    {
        id: "cow-manure-1kg",
        title: "Cow Manure - 1 kg",
        price: "₹30",
        image: "/assets/img/farm-soul.png",
        category: "Gau Seva",
        description: "Organic manure from Desi Gir cows for your garden.",
        slug: "cow-manure-1kg",
        sku: "AMRIT-GAU-001",
    },
    {
        id: "cow-dung-cakes-2pcs",
        title: "Upla (Cow Dung Cakes) - 2 pcs",
        price: "₹100",
        image: "/assets/img/farm-soul.png",
        category: "Gau Seva",
        description: "Traditionally dried Cow Dung cakes for rituals and fuel.",
        slug: "cow-dung-cakes-2pcs",
        sku: "AMRIT-GAU-002",
    },
    {
        id: "gaumutra-1l",
        title: "Gaumutra - 1 L",
        price: "₹100",
        image: "/assets/img/farm-soul.png",
        category: "Gau Seva",
        description: "Distilled Gaumutra for spiritual and medicinal use.",
        slug: "gaumutra-1l",
        sku: "AMRIT-GAU-003",
    },
];

export type Product = (typeof products)[0];

export const categories = [
    { id: "all", label: "All Products", icon: "LayoutGrid" },
    { id: "dairy", label: "A2 Dairy", icon: "Milk" },
    { id: "oils", label: "Wood Pressed Oils", icon: "Droplet" },
    { id: "atta", label: "Stone Ground Atta", icon: "Wheat" },
    { id: "honey", label: "Raw Honey", icon: "Hexagon" },
    { id: "wellness", label: "Wellness", icon: "Package" },
] as const;
