@echo off
echo Downloading Simple Honey...
curl -k "https://image.pollinations.ai/prompt/straight%%20glass%%20jar%%20of%%20honey%%20white%%20background?width=1024&height=1024&nologo=true" -o public/assets/img/products/amrit_honey_glass_jar_v4.png
echo Downloading Simple Mint...
curl -k "https://image.pollinations.ai/prompt/mint%%20essential%%20oil%%20bottle%%20white%%20background?width=1024&height=1024&nologo=true" -o public/assets/img/products/amrit_mint_oil_v4.png
echo Downloading Simple Lemongrass...
curl -k "https://image.pollinations.ai/prompt/lemongrass%%20essential%%20oil%%20bottle%%20white%%20background?width=1024&height=1024&nologo=true" -o public/assets/img/products/amrit_lemongrass_oil_v4.png
echo Done.
