/**
 * Subscription Management Schema for Sanity
 */

export default {
    name: 'subscription',
    title: 'Subscriptions',
    type: 'document',
    fields: [
        {
            name: 'subscriptionId',
            title: 'Subscription ID',
            type: 'string',
            description: 'Unique subscription identifier',
            validation: (Rule: any) => Rule.required(),
        },
        {
            name: 'customer',
            title: 'Customer Details',
            type: 'object',
            fields: [
                { name: 'name', title: 'Name', type: 'string' },
                { name: 'email', title: 'Email', type: 'string' },
                { name: 'phone', title: 'Phone', type: 'string' },
                { name: 'address', title: 'Address', type: 'text' },
            ],
        },
        {
            name: 'product',
            title: 'Product',
            type: 'object',
            fields: [
                { name: 'productId', title: 'Product ID', type: 'string' },
                { name: 'name', title: 'Product Name', type: 'string' },
                { name: 'variant', title: 'Variant', type: 'string' },
                { name: 'quantity', title: 'Quantity', type: 'number' },
                { name: 'price', title: 'Price', type: 'number' },
            ],
        },
        {
            name: 'plan',
            title: 'Subscription Plan  ',
            type: 'object',
            fields: [
                {
                    name: 'frequency',
                    title: 'Delivery Frequency',
                    type: 'string',
                    options: {
                        list: [
                            { title: 'Daily', value: 'daily' },
                            { title: 'Every 2 Days', value: 'every_2_days' },
                            { title: 'Weekly', value: 'weekly' },
                            { title: 'Bi-Weekly', value: 'bi_weekly' },
                            { title: 'Monthly', value: 'monthly' },
                        ],
                    },
                },
                { name: 'startDate', title: 'Start Date', type: 'date' },
                { name: 'endDate', title: 'End Date (Optional)', type: 'date' },
                { name: 'nextDelivery', title: 'Next Delivery Date', type: 'datetime' },
            ],
        },
        {
            name: 'status',
            title: 'Status',
            type: 'string',
            options: {
                list: [
                    { title: 'Active', value: 'active' },
                    { title: 'Paused', value: 'paused' },
                    { title: 'Cancelled', value: 'cancelled' },
                    { title: 'Expired', value: 'expired' },
                ],
            },
            initialValue: 'active',
        },
        {
            name: 'paymentMethod',
            title: 'Payment Method',
            type: 'string',
            options: {
                list: [
                    { title: 'CCAvenue Recurring', value: 'ccavenue_recurring' },
                    { title: 'COD', value: 'cod' },
                ],
            },
        },
        {
            name: 'ccavenueData',
            title: 'CCAvenue Recurring Details',
            type: 'object',
            fields: [
                { name: 'subscriptionRefNo', title: 'CCAvenue Subscription Ref', type: 'string' },
                { name: 'mandateId', title: 'Mandate ID', type: 'string' },
                { name: 'cardToken', title: 'Card Token', type: 'string' },
            ],
        },
        {
            name: 'deliveryInstructions',
            title: 'Delivery Instructions',
            type: 'text',
        },
        {
            name: 'pauseHistory',
            title: 'Pause History',
            type: 'array',
            of: [{
                type: 'object',
                fields: [
                    { name: 'pausedAt', title: 'Paused At', type: 'datetime' },
                    { name: 'resumedAt', title: 'Resumed At', type: 'datetime' },
                    { name: 'reason', title: 'Reason', type: 'string' },
                ],
            }],
        },
        {
            name: 'orders',
            title: 'Related Orders',
            type: 'array',
            of: [{ type: 'reference', to: [{ type: 'order' }] }],
            description: 'All orders generated by this subscription',
        },
        {
            name: 'createdAt',
            title: 'Created At',
            type: 'datetime',
        },
        {
            name: 'updatedAt',
            title: 'Updated At',
            type: 'datetime',
        },
    ],
    preview: {
        select: {
            customerName: 'customer.name',
            productName: 'product.name',
            frequency: 'plan.frequency',
            status: 'status',
        },
        prepare({ customerName, productName, frequency, status }: any) {
            return {
                title: `${customerName} - ${productName}`,
                subtitle: `${frequency} | ${status}`,
            };
        },
    },
};
